import turtle
window = turtle.Screen()
window.bgcolor("light yellow")
window.title("Turtle")
t = turtle.Turtle()
t.penup()
t.setpos(-20,40)
t.pendown()
t.pensize(15)
t.pencolor("pink")
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
t.right(90)
t.forward(200)
turtle.done()
