import turtle
window = turtle.Screen()
window.bgcolor("light yellow")
window.title("Turtle")
t = turtle.Turtle()
turtle.color("darkblue")
style = ('Times New Roman' , 90 , 'normal')
turtle.write('Pranit E-Learnings', font= style, align= 'center' )
turtle.hideturtle()
turtle.done()
